### ISSUE TITLE
Can you please Hacktoberfest topic to this repository?

### ISSUE THREAD

**Issue by dariy-vel** [alex2844/youtube-music#5]
I'm interested in this repo and would like to contribute a bit. Would highly appreciate if you add 'Hacktoberfest' topic as I'm taking part in that event.

**Comment by alex2844** [comment]
сомневаюсь что данный проект подойдет для данного мероприятия - ведь пиратство не законо - и гитхаб может в любой момент заблокировать этот репозиторий

I doubt that this project will be suitable for this event - after all, piracy is not legal - and github can block this repository at any time

**Comment by dariy-vel** [comment]
Do you think this app will be interpreted as piracy?

**Comment by alex2844** [comment]
Yes
